# Header
menu:
  Home: /
  Archives: /archives
  GitHub: https://github.com/deptno
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: false
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# Miscellaneous
google_analytics: UA-74859643-1
twitter: deptno
google_plus: 
fb_admins: 
fb_app_id:
